# Importación de librerias necesarias

In [39]:
#Inporatamos la libreria pandas
import pandas as pd 
#Inporatamos la libreria seaborn
import seaborn as sns
#Inporatamos la libreria numpy
import numpy as np
#Importamos LabelEncoder desde la libreria sklearn
from sklearn.preprocessing import LabelEncoder
#Importamos train_test_split desde la libreria sklearn
from sklearn.model_selection import train_test_split
#Importamos MinMaxScaler desde la libreria sklearn
from sklearn.preprocessing import MinMaxScaler
#Importamos la libreria matplotlib
import matplotlib.pyplot as plt
#Importamos GaussianNB desde la libreria sklearn
from sklearn.naive_bayes import GaussianNB
#Importamos Metric desde la libreria sklearn
from sklearn import metrics
#Importamos la libreria collections
import collections
#Importamos hiden markov model desde la libreria hmmlearn
from hmmlearn import hmm
#Importamos confusion_matrix desde la libreria sklearn
from sklearn.metrics import confusion_matrix
# Importamos acurracy_score desde la libreria sklearn
from sklearn.metrics import accuracy_score
#Importamos recall_score desde la libreria sklearn
from sklearn.metrics import recall_score
#Importamos precision_score desde la libreria sklearn
from sklearn.metrics import precision_score
#Importamos f1_score desde la libreria sklearn
from sklearn.metrics import f1_score

In [40]:
#Carga del dataset
data_proyecto = pd.read_csv('2020_datos_violencia_delictiva.csv')

In [41]:
#Mostrar el dataset
data_proyecto.head(1000)

,Año,Clave_Ent,Entidad,Cve. Municipio,Municipio,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,...,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2020,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,2,...,3,3,2,3,5,2,1,1,1,1
1,2020,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,0,...,2,0,2,0,1,1,0,0,1,0
2,2020,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,1,...,1,0,2,2,1,2,0,2,0,0
3,2020,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,0,...,0,0,0,0,0,0,0,0,0,0
4,2020,1,Aguascalientes,1001,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020,1,Aguascalientes,1011,San Francisco de los Romo,La vida y la Integridad corporal,Lesiones,Lesiones culposas,En accidente de tránsito,4,...,2,1,1,3,2,2,1,1,6,1
996,2020,1,Aguascalientes,1011,San Francisco de los Romo,La vida y la Integridad corporal,Lesiones,Lesiones culposas,Con otro elemento,0,...,0,0,0,0,0,0,0,0,0,0
997,2020,1,Aguascalientes,1011,San Francisco de los Romo,La vida y la Integridad corporal,Lesiones,Lesiones culposas,No especificado,1,...,1,1,0,2,1,1,2,0,2,3
998,2020,1,Aguascalientes,1011,San Francisco de los Romo,La vida y la Integridad corporal,Feminicidio,Feminicidio,Con arma de fuego,0,...,0,0,0,0,0,0,0,0,0,0
999,2020,1,Aguascalientes,1011,San Francisco de los Romo,La vida y la Integridad corporal,Feminicidio,Feminicidio,Con arma blanca,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
#Aplicación de la funcion describe para ver información estadística del dataset
data_proyecto.describe()

,Año,Clave_Ent,Cve. Municipio,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
count,242158.0,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000,242158.000000
mean,2020.0,19.245650,19357.386483,0.684722,0.692135,0.707749,0.494747,0.503233,0.585448,0.636378,0.653330,0.665371,0.705589,0.640549,0.633999
std,0.0,7.356573,7373.231839,7.913517,7.874925,8.217510,6.023346,6.055441,6.879104,7.500991,7.690377,7.580925,7.951791,7.417011,7.707886
min,2020.0,1.000000,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2020.0,14.000000,14081.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2020.0,20.000000,20231.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2020.0,24.000000,24031.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2020.0,32.000000,32058.000000,965.000000,906.000000,1060.000000,840.000000,774.000000,958.000000,1019.000000,1140.000000,1099.000000,1023.000000,1156.000000,1394.000000

In [43]:
#Aplicación de la funció n count para ver la cantidad de registros del dataset
data_proyecto.count()

Año                       242158
Clave_Ent                 242158
Entidad                   242158
Cve. Municipio            242158
Municipio                 242158
Bien jurídico afectado    242158
Tipo de delito            242158
Subtipo de delito         242158
Modalidad                 242158
Enero                     242158
Febrero                   242158
Marzo                     242158
Abril                     242158
Mayo                      242158
Junio                     242158
Julio                     242158
Agosto                    242158
Septiembre                242158
Octubre                   242158
Noviembre                 242158
Diciembre                 242158
dtype: int64

In [44]:
#Proceso de eliminación de registros reduciendo su cantidad a 4000 samples
df = data_proyecto.drop(range(4000,242158), axis=0)

In [45]:
#Aplicación de la función describe al nuevo dataset
df.describe()

,Año,Clave_Ent,Cve. Municipio,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
count,4000.0,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.00000,4000.000000,4000.000000,4000.00000,4000.000000,4000.00000
mean,2020.0,3.040000,3045.227000,3.509500,3.435000,3.681000,2.313000,2.547500,2.960000,3.28450,3.250000,3.264750,3.40525,3.085750,3.05275
std,0.0,1.527411,1527.368124,22.220348,21.917935,23.803548,16.481943,17.783723,19.826804,22.00682,21.195136,20.538917,20.83011,19.441731,21.99253
min,2020.0,1.000000,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.00000
25%,2020.0,1.000000,1011.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.00000
50%,2020.0,3.000000,3009.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.00000
75%,2020.0,4.000000,4010.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.00000
max,2020.0,5.000000,5009.000000,606.000000,655.000000,666.000000,624.000000,623.000000,725.000000,724.00000,622.000000,545.000000,516.00000,521.000000,893.00000

In [46]:
#Mostrar la información del nuevo dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     4000 non-null   int64
 1   Clave_Ent               4000 non-null   int64
 2   Entidad                 4000 non-null   object
 3   Cve. Municipio          4000 non-null   int64
 4   Municipio               4000 non-null   object
 5   Bien jurídico afectado  4000 non-null   object
 6   Tipo de delito          4000 non-null   object
 7   Subtipo de delito       4000 non-null   object
 8   Modalidad               4000 non-null   object
 9   Enero                   4000 non-null   int64
 10  Febrero                 4000 non-null   int64
 11  Marzo                   4000 non-null   int64
 12  Abril                   4000 non-null   int64
 13  Mayo                    4000 non-null   int64
 14  Junio                   4000 non-null   int64
 15  Julio                   4000 non-null   int64
 16  Agosto                  4000 non-null   int64
 17  Septiembre              4000 non-null   int64
 18  Octubre                 4000 non-null   int64
 19  Noviembre               4000 non-null   int64
 20  Diciembre               4000 non-null   int64
dtypes: int64(15), object(6)
memory usage: 656.4+ KB

# Limpieza del dataset

In [47]:
#Aplicación de la función nunique para identificar las variable categoricas
df.nunique()

Año                         1
Clave_Ent                   5
Entidad                     5
Cve. Municipio             41
Municipio                  41
Bien jurídico afectado      7
Tipo de delito             40
Subtipo de delito          55
Modalidad                  59
Enero                     100
Febrero                    94
Marzo                      96
Abril                      81
Mayo                       80
Junio                      94
Julio                      94
Agosto                     98
Septiembre                 97
Octubre                   102
Noviembre                  95
Diciembre                  91
dtype: int64

In [48]:
#Verificamos la existencia de datos nulos
df.isnull().sum()

Año                       0
Clave_Ent                 0
Entidad                   0
Cve. Municipio            0
Municipio                 0
Bien jurídico afectado    0
Tipo de delito            0
Subtipo de delito         0
Modalidad                 0
Enero                     0
Febrero                   0
Marzo                     0
Abril                     0
Mayo                      0
Junio                     0
Julio                     0
Agosto                    0
Septiembre                0
Octubre                   0
Noviembre                 0
Diciembre                 0
dtype: int64

In [49]:
#Eliminamos las columnas que no utilizaremos
df1 = df.drop(columns=['Entidad','Municipio', 'Bien jurídico afectado','Subtipo de delito','Modalidad'])

In [50]:
#Mostramos la nueva data
df1

,Año,Clave_Ent,Cve. Municipio,Tipo de delito,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2020,1,1001,Homicidio,2,6,3,3,2,3,5,2,1,1,1,1
1,2020,1,1001,Homicidio,0,1,2,0,2,0,1,1,0,0,1,0
2,2020,1,1001,Homicidio,1,1,1,0,2,2,1,2,0,2,0,0
3,2020,1,1001,Homicidio,0,0,0,0,0,0,0,0,0,0,0,0
4,2020,1,1001,Homicidio,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,2020,5,5009,Fraude,2,1,0,2,0,0,0,0,2,1,0,1
3996,2020,5,5009,Abuso de confianza,0,4,3,0,3,0,2,3,1,4,2,0
3997,2020,5,5009,Extorsión,0,0,0,0,0,0,0,0,0,0,0,0
3998,2020,5,5009,Daño a la propiedad,10,4,5,4,1,0,1,3,2,5,5,4
3999,2020,5,5009,Despojo,0,0,1,2,2,0,2,1,1,1,2,0

In [51]:
#Verificamos la existencia  de datos vacios (longitud = 0)
df1.isna().sum()

Año               0
Clave_Ent         0
Cve. Municipio    0
Tipo de delito    0
Enero             0
Febrero           0
Marzo             0
Abril             0
Mayo              0
Junio             0
Julio             0
Agosto            0
Septiembre        0
Octubre           0
Noviembre         0
Diciembre         0
dtype: int64

# Tranformación de datos categoricos a la nueva data

In [52]:
#Identificamos los valores unicos para cada categoria
df1.nunique()

Año                 1
Clave_Ent           5
Cve. Municipio     41
Tipo de delito     40
Enero             100
Febrero            94
Marzo              96
Abril              81
Mayo               80
Junio              94
Julio              94
Agosto             98
Septiembre         97
Octubre           102
Noviembre          95
Diciembre          91
dtype: int64

In [53]:
#Aplicación de label encoder para eliminar las variables categoricas 
'''Se convierte de tipo objeto a categórico'''
df1 = df1.astype('category')
'''Se visualiza el cambio en el tipo de datos de las características'''
df1.dtypes

Año               category
Clave_Ent         category
Cve. Municipio    category
Tipo de delito    category
Enero             category
Febrero           category
Marzo             category
Abril             category
Mayo              category
Junio             category
Julio             category
Agosto            category
Septiembre        category
Octubre           category
Noviembre         category
Diciembre         category
dtype: object

In [54]:
'''Se importa la librería de LabelEndocer para transformar de categórico a numérico'''
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
for column in df1.columns:
    df1[column] = labelencoder.fit_transform(df1[column])

df1.head()

,Año,Clave_Ent,Cve. Municipio,Tipo de delito,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,0,0,0,18,2,6,3,3,2,3,5,2,1,1,1,1
1,0,0,0,18,0,1,2,0,2,0,1,1,0,0,1,0
2,0,0,0,18,1,1,1,0,2,2,1,2,0,2,0,0
3,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,18,0,0,0,0,0,0,0,0,0,0,0,0

In [55]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Año             4000 non-null   int64
 1   Clave_Ent       4000 non-null   int64
 2   Cve. Municipio  4000 non-null   int64
 3   Tipo de delito  4000 non-null   int32
 4   Enero           4000 non-null   int64
 5   Febrero         4000 non-null   int64
 6   Marzo           4000 non-null   int64
 7   Abril           4000 non-null   int64
 8   Mayo            4000 non-null   int64
 9   Junio           4000 non-null   int64
 10  Julio           4000 non-null   int64
 11  Agosto          4000 non-null   int64
 12  Septiembre      4000 non-null   int64
 13  Octubre         4000 non-null   int64
 14  Noviembre       4000 non-null   int64
 15  Diciembre       4000 non-null   int64
dtypes: int32(1), int64(15)
memory usage: 484.5 KB

In [65]:
nuevo_df = pd.DataFrame(df1)
nuevo_df.to_csv('nuevo_violencias2020.csv')

# Preprocesamiento de los datos

In [66]:
# Asignamos las variables dependientes
X = nuevo_df[['Año', 'Clave_Ent', 'Cve. Municipio', 'Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre','Octubre','Noviembre','Diciembre']]

# Asignamos la variable objetivo
y = nuevo_df[['Tipo de delito']]

# Estandarización de la data

In [67]:
### Estandarización de la data ###
from sklearn.preprocessing import StandardScaler
VariablesEntradaScaler=StandardScaler()
VariableObjetivoScaler=StandardScaler()

In [68]:
#Almacenamiento del objeto de ajuste para referencia posterior
VariablesEntradaFit=VariablesEntradaScaler.fit(X)
VariableObjetivoFit=VariableObjetivoScaler.fit(y)

In [69]:
#Generación de los valores estandarizados de X e y
X=VariablesEntradaFit.transform(X)
y=VariableObjetivoFit.transform(y)

In [70]:
# Asignamos los datos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [71]:
# Verificamos la cantidad de datos de entrenamiento y prueba
X_train.shape, y_test.shape

((2800, 15), (1200, 1))

# Naive Bayes

In [72]:
# Instanciamos el algoritmo gauciano de Naive Bayes
gnb = GaussianNB()

In [75]:
# Alimentamos nuestro modelo con los datos de entrenamiento
# y obtenemos la predicción
y_pred_NB = gnb.fit(X_train, y_train.ravel()).predict(X_test)

ValueError: Unknown label type: (array([-2.53474863, -2.43135281, -2.32795699, -2.22456116, -2.12116534,
       -2.01776951, -1.91437369, -1.81097786, -1.70758204, -1.60418622,
       -1.50079039, -1.39739457, -1.29399874, -1.19060292, -1.08720709,
       -0.98381127, -0.88041544, -0.77701962, -0.6736238 , -0.57022797,
       -0.46683215, -0.36343632, -0.2600405 , -0.15664467, -0.05324885,
        0.05014697,  0.1535428 ,  0.25693862,  0.36033445,  0.46373027,
        0.5671261 ,  0.67052192,  0.77391775,  0.87731357,  0.98070939,
        1.08410522,  1.18750104,  1.29089687,  1.39429269,  1.49768852]),)

In [76]:
# Mostramos el accuracy del modelo Naive Bayes
print("Accuracy Naive Bayes:", metrics.accuracy_score(y_test, y_pred_NB))

ValueError: Classification metrics can't handle a mix of continuous and multiclass targets

# Hidden Markov Model

In [24]:
# Instanciamos el modelo Hidden Markov Model
model = hmm.GaussianHMM(n_components = 3, covariance_type = "diag", n_iter = 50, random_state = 42)

# Entrenamos el modelo con los datos de entrenamiento
model.fit(X_train)

GaussianHMM(n_components=3, n_iter=50, random_state=42)

In [25]:
# realizamos la prueba de predicción del model
y_pred_HMM = model.predict(X_test)

In [26]:
# Mostramos el accuracy del modelo Hidden Markov Model
print("Accuracy Hidden Markov Model:", metrics.accuracy_score(y_test, y_pred_HMM))

Accuracy Hidden Markov Model: 0.011666666666666667

# Matriz de confusión (Naive Bayes)

In [29]:
#Cramos la matriz de confusión
print(confusion_matrix(y_test, y_pred_NB))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]]